import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";


const Avenir = localFont({
  src: [
    {
      path: "./fonts/Avenir-Next-reg.ttf",
      weight: "600",
      style: "normal",
    },
  ],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <head>
        <meta />
      </head>


      <body className={` ${Avenir.variable}`}>
        <Header/>
        <div className="page-content">
          {children}
        </div>
        
        <Footer/>
      </body>
    </html>
  );
}
